# TCL File Generated by Component Editor 22.1
# Mon Aug 07 19:21:41 PDT 2023
# DO NOT MODIFY


# 
# tdk "tdc" v1.0
# Tyler Sheaves 2023.08.07.19:21:41
# AVMM-ST source TDC
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module tdk
# 
set_module_property DESCRIPTION "AVMM-ST source TDC"
set_module_property NAME tdk
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP KRG
set_module_property AUTHOR "Tyler Sheaves"
set_module_property DISPLAY_NAME tdc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tdc_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file carry_chain.v VERILOG PATH ./hdl/carry_chain.v
add_fileset_file carry_top.v VERILOG PATH ./hdl/carry_top.v
add_fileset_file pulse_gen.sv SYSTEM_VERILOG PATH ./hdl/pulse_gen.sv
add_fileset_file tdc_top.sv SYSTEM_VERILOG PATH ./hdl/tdc_top.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter C_OUT_WIDTH INTEGER 256 "Must be a divisor of 256. "
set_parameter_property C_OUT_WIDTH DEFAULT_VALUE 256
set_parameter_property C_OUT_WIDTH DISPLAY_NAME C_OUT_WIDTH
set_parameter_property C_OUT_WIDTH TYPE INTEGER
set_parameter_property C_OUT_WIDTH UNITS None
set_parameter_property C_OUT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_OUT_WIDTH DESCRIPTION "Must be a divisor of 256. "
set_parameter_property C_OUT_WIDTH HDL_PARAMETER true
add_parameter C_SYNC_DEPTH INTEGER 2 ""
set_parameter_property C_SYNC_DEPTH DEFAULT_VALUE 2
set_parameter_property C_SYNC_DEPTH DISPLAY_NAME C_SYNC_DEPTH
set_parameter_property C_SYNC_DEPTH TYPE INTEGER
set_parameter_property C_SYNC_DEPTH UNITS None
set_parameter_property C_SYNC_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_SYNC_DEPTH DESCRIPTION ""
set_parameter_property C_SYNC_DEPTH HDL_PARAMETER true
add_parameter TECHNOLOGY STRING 28nm
set_parameter_property TECHNOLOGY DEFAULT_VALUE 28nm
set_parameter_property TECHNOLOGY DISPLAY_NAME TECHNOLOGY
set_parameter_property TECHNOLOGY TYPE STRING
set_parameter_property TECHNOLOGY UNITS None
set_parameter_property TECHNOLOGY HDL_PARAMETER true
add_parameter REVERSE INTEGER 0 "Reverse the order of the paked TDC samples. May be required for different DMA configurations."
set_parameter_property REVERSE DEFAULT_VALUE 0
set_parameter_property REVERSE DISPLAY_NAME REVERSE
set_parameter_property REVERSE WIDTH ""
set_parameter_property REVERSE TYPE INTEGER
set_parameter_property REVERSE UNITS None
set_parameter_property REVERSE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REVERSE DESCRIPTION "Reverse the order of the paked TDC samples. May be required for different DMA configurations."
set_parameter_property REVERSE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk_capt
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clk_capt
# 
add_interface clk_capt clock end
set_interface_property clk_capt clockRate 0
set_interface_property clk_capt ENABLED true
set_interface_property clk_capt EXPORT_OF ""
set_interface_property clk_capt PORT_NAME_MAP ""
set_interface_property clk_capt CMSIS_SVD_VARIABLES ""
set_interface_property clk_capt SVD_ADDRESS_GROUP ""

add_interface_port clk_capt clk_capt clk Input 1


# 
# connection point clk_launch
# 
add_interface clk_launch clock end
set_interface_property clk_launch clockRate 0
set_interface_property clk_launch ENABLED true
set_interface_property clk_launch EXPORT_OF ""
set_interface_property clk_launch PORT_NAME_MAP ""
set_interface_property clk_launch CMSIS_SVD_VARIABLES ""
set_interface_property clk_launch SVD_ADDRESS_GROUP ""

add_interface_port clk_launch clk_launch clk Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clk_launch
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink S_AVST_DATA data Input 8
add_interface_port avalon_streaming_sink S_AVST_VALID valid Input 1
add_interface_port avalon_streaming_sink S_AVST_READY ready Output 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clk_capt
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source M_AVST_DATA data Output 256
add_interface_port avalon_streaming_source M_AVST_VALID valid Output 1
add_interface_port avalon_streaming_source M_AVST_READY ready Input 1

