# TCL File Generated by Component Editor 22.1
# Sun Aug 06 17:12:41 PDT 2023
# DO NOT MODIFY


# 
# ip_sync "ip_sync" v1.0
# Tyler Sheaves 2023.08.06.17:12:41
# Pipelining alignment for syncing IPs
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ip_sync
# 
set_module_property DESCRIPTION "Pipelining alignment for syncing IPs"
set_module_property NAME ip_sync
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP KRG
set_module_property AUTHOR "Tyler Sheaves"
set_module_property DISPLAY_NAME ip_sync
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ip_sync
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ip_sync.sv SYSTEM_VERILOG PATH ./hdl/ip_sync.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ADDR_TRIGGER STD_LOGIC_VECTOR 0
set_parameter_property ADDR_TRIGGER DEFAULT_VALUE 0
set_parameter_property ADDR_TRIGGER DISPLAY_NAME ADDR_TRIGGER
set_parameter_property ADDR_TRIGGER WIDTH 9
set_parameter_property ADDR_TRIGGER TYPE STD_LOGIC_VECTOR
set_parameter_property ADDR_TRIGGER UNITS None
set_parameter_property ADDR_TRIGGER ALLOWED_RANGES 0:511
set_parameter_property ADDR_TRIGGER HDL_PARAMETER true
add_parameter DATA_TRIGGER STD_LOGIC_VECTOR 2
set_parameter_property DATA_TRIGGER DEFAULT_VALUE 2
set_parameter_property DATA_TRIGGER DISPLAY_NAME DATA_TRIGGER
set_parameter_property DATA_TRIGGER WIDTH 34
set_parameter_property DATA_TRIGGER TYPE STD_LOGIC_VECTOR
set_parameter_property DATA_TRIGGER UNITS None
set_parameter_property DATA_TRIGGER ALLOWED_RANGES 0:17179869183
set_parameter_property DATA_TRIGGER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 1
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master M_AVMM_ADDR address Output 8
add_interface_port avalon_master M_AVMM_RDATA readdata Input 32
add_interface_port avalon_master M_AVMM_W write Output 1
add_interface_port avalon_master M_AVMM_WDATA writedata Output 32
add_interface_port avalon_master M_AVMM_WAITREQUEST waitrequest Input 1
add_interface_port avalon_master M_AVMM_BURSTCOUNT burstcount Output 1
add_interface_port avalon_master M_AVMM_BYTEENABLE byteenable Output 4
add_interface_port avalon_master M_AVMM_READATAVALID readdatavalid Input 1
add_interface_port avalon_master M_AVMM_R read Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave S_AVMM_ADDR address Input 8
add_interface_port avalon_slave S_AVMM_RDATA readdata Output 32
add_interface_port avalon_slave S_AVMM_W write Input 1
add_interface_port avalon_slave S_AVMM_WDATA writedata Input 32
add_interface_port avalon_slave S_AVMM_WAITREQUEST waitrequest Output 1
add_interface_port avalon_slave S_AVMM_R read Input 1
add_interface_port avalon_slave S_AVMM_READATAVALID readdatavalid Output 1
add_interface_port avalon_slave S_AVMM_BURSTCOUNT burstcount Input 1
add_interface_port avalon_slave S_AVMM_BYTEENABLE byteenable Input 4
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source M_AVST_DATA data Output 8
add_interface_port avalon_streaming_source M_AVST_READY ready Input 1
add_interface_port avalon_streaming_source M_AVST_VALID valid Output 1

